name: ols_mobile
description: Loyalty mobile app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1
  sqflite: ^1.0.0
  path_provider: ^0.4.1
  flutter_rating_bar: ^1.1.1
  rxdart: ^0.20.0
  google_maps_flutter: ^0.5.7
  splashscreen: ^1.2.0
  dio: ^2.1.2
  shared_preferences: ^0.5.2
  connectivity: ^0.4.3
  event_bus: any
  json_annotation: ^2.0.0
  flutter_easyrefresh: ^1.2.7
  flutter_facebook_login: ^2.0.0
  google_sign_in: ^4.0.7
  modal_progress_hud: ^0.1.3
  auto_size_text: ^1.1.2
  flutter_calendar_carousel: ^1.3.18
  fast_qr_reader_view:
    git:
      url: git://github.com/facundomedica/fast_qr_reader_view.git
  qr_flutter: ^2.1.0
  firebase_messaging: 5.1.4
  device_info: ^0.4.0+2
  frideos:
  random_string: ^0.0.2
  url_launcher: ^5.0.3
  pull_to_refresh_notification:
  like_button: ^0.1.7
  geolocator: '^5.0.0'
  flutter_cupertino_date_picker: ^1.0.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  image_picker: 0.6.1+8
  sticky_headers: ^0.1.8
  flutter_picker: ^1.0.13
  shimmer: ^1.0.0
  pull_to_refresh: ^1.5.0
  flutter_spinkit: ^3.1.0
  flutter_page_transition: ^0.1.0
  scaling_header: ^1.1.1
  local_auth: ^0.5.2+3
  get_it: ^1.0.3+2
  flutter_secure_storage:
  country_code_picker: ^1.1.7
  fluttertoast: ^3.1.0
  expandable: ^3.0.0+1
  percent_indicator: "^1.0.14"
  flutter_statusbarcolor: ^0.2.2
  flutter_slidable: "^0.5.3"
  badges: ^1.1.0
  device_calendar: ^0.0.2
  flutter_i18n: ^0.6.4
  image_cropper: ^1.0.2
  flutter_svg: ^0.14.1
  date_range_picker: ^1.0.5
  barcode_flutter: ^1.0.2
flutter_html: ^0.11.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  pin_input_text_field: ^2.0.0
  flutter_html: ^0.11.0
  flutter_swiper: ^1.1.6

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/loyalty/app_launcher_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # module:
  #   iosBundleIdentifier: com.oe.oev.ols.mbf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/loyalty/
    - assets/svg/
    - resources/langs/vi.json
    - resources/langs/en.json
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf
          weight: 700
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages